# Introdução à Data Science com Python - Data ICMC-USP

Esse material foi desenvolvido pelo Data, grupo de extensão de aprendizado e ciência de dados compostos por alunos do Instituto de Ciências Matemáticas e de Computação da USP.

Esse notebook é acompanhado de um curso em video, que pode ser encontrado em [aqui](https://www.youtube.com/playlist?list=PLFE-LjWAAP9SfEuLXf3qrpw4szKWjlYq9)

Para saber mais sobre as atividades do Data entre no nosso site e nos siga e nossas redes sociais:
- [Site](http://data.icmc.usp.br/)
- [Twitter](https://twitter.com/data_icmc)
- [LinkedIn](https://www.linkedin.com/school/data-icmc/)
- [Facebook](https://www.facebook.com/dataICMC/)

Aproveite o material!

## Exercícios NumPy

O objetivo desse notebook é ajudar na fixação dos conteúdos que passamos nas aulas de NumPy. Esse material foi preparado para acompanhar o que foi passado nos videos, e em breve teremos a divulgação das resuluções com um vídeo de explicação.

In [ ]:
# Importando a biblioteca
import numpy as np

### Arrays

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

b = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

c = np.zeros((3,4))

In [ ]:
# Pense em qual é a shape de cada um dos arrays acima
# Depois de pensar imprima cada um deles para conferir sua resposta

print (np.shape(a))
print (np.shape(b))
print (np.shape(c))

(7,)
(2, 4)
(3, 4)


In [ ]:
# Crie um array de uma dimenção com 20 elementos inteiros aletórios entre 0 e 23bb
d= np.random.randint(23, size =(20))

print (np.shape (d))

d

(20,)


array([16, 22, 12, 20, 10,  2, 11,  1, 17,  7,  1,  6,  1,  7,  8, 20, 19,
        3,  5, 12])

In [ ]:
# Crie um array de uns com shape (4, 5)
np.random.random ((4,5))


array([[0.73341779, 0.35987718, 0.82763228, 0.24882814, 0.62736712],
       [0.30689685, 0.35887629, 0.6435231 , 0.32972576, 0.05759992],
       [0.67207065, 0.94692425, 0.6950105 , 0.41660956, 0.23445555],
       [0.1377855 , 0.93853647, 0.27990991, 0.37066362, 0.37941307]])

In [ ]:
# Crie um array shape (4, 2) onde cada entrada vale 77
e= np.ones((4,2))
print (e)
e*77

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


array([[77., 77.],
       [77., 77.],
       [77., 77.],
       [77., 77.]])

In [ ]:
np.ones ((4,2)) *77

array([[77., 77.],
       [77., 77.],
       [77., 77.],
       [77., 77.]])

In [ ]:
# Gere um array chamado my_sequence com os numeros 0, 10, 20, 30, ..., 90, 100]

my_sequence = np.array ([0,10,20,30,40,50,60,70,80,90,100])
my_sequence


array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

### Indexando

In [ ]:
my_array = np.random.randint(50, size=(15,))
print(my_array)

[ 5  4 18 21  9 35 17 23 29 28 13 46  8  6 33]


In [ ]:
# Selecione todos os elementos entre o quinto e o decimo primeiro (intervalo fechado)
my_array [5:12]

array([35, 17, 23, 29, 28, 13, 46])

In [ ]:
# Selecione todos os elementos maiores que 20
m_20= my_array>20
my_array [m_20]


array([21, 35, 23, 29, 28, 46, 33])

In [50]:
maior_que_20 = my_array > 20
print(maior_que_20)
valores = my_array[maior_que_20]
print(valores)

[False False False  True False  True False  True  True  True False  True
 False False  True]
[21 35 23 29 28 46 33]


In [51]:
my_matrix = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])

In [54]:
# Selecione o elemento na primeira linha da terceira coluna
my_matrix [0,2]

3

In [55]:
# Selecione o elemento na primeira linha da ultima coluna
my_matrix [0,3]

4

In [64]:
# Selecione os elementos da matriz para obter o seguinte
# [[6, 7] e [10, 11]]

my_matrix [1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [63]:
# Selecione os elementos da matriz para obter o seguinte
# [[2, 3, 4] e [6, 7, 8]]

my_matrix [0:2, 1:4]

array([[2, 3, 4],
       [6, 7, 8]])

In [71]:
# Selecione os elementos da ultima coluna inteira

my_matrix [:, 3]

array([ 4,  8, 12, 16])

In [72]:
# Selecione os elementos da 2a linha inteira
my_matrix [1, :]

array([5, 6, 7, 8])

### Operações

In [75]:
my_array = np.random.randint(10, size=(5,))
print(my_array)

[0 5 7 3 6]


In [76]:
# Some 10 a todos os elementos de my_array

my_array +10

array([10, 15, 17, 13, 16])

In [77]:
# Multiplique todos os elementos de my_array por 4
my_array *4

array([ 0, 20, 28, 12, 24])

In [79]:
# Obtenha a soma de todos os elementos de my_array
my_array.sum ()


21

In [80]:
np.sum (my_array)

21

In [83]:
# Obtenha a média de todos os elementos de my_array
my_array.mean()

4.2

In [81]:
np.mean(my_array)

4.2

In [84]:
# Obtenha o indice do maior elemento de my_array
my_array.max()

7

In [85]:
np.max (my_array)

7

In [109]:
my_array = np.random.randint(10, size=(5,))
my_other_array = np.random.randint(10, size=(5,))
print(my_array, '\n')
print(my_other_array)

[2 7 1 0 6] 

[8 4 5 8 0]


In [87]:
# Some my_array elemento por elemento em cada linha de my_other_array
my_array + my_other_array


array([15,  1,  5,  2, 13])

In [113]:
# Faça a multiplicação entre my_other_array e my_array

# como nesse caso as matrizes tem o mesmo formato posso usar tando o dot() quanto o multiply()

# dot()-> produto das 2 matrizes
# multiply()-> multiplicação elemento a elemento das 2 matrizes


print (np.multiply(my_other_array,my_array))

print (np.multiply(my_array, my_other_array))

print (np.dot(my_other_array,my_array))

[16 28  5  0  0]
[16 28  5  0  0]
49


In [114]:
my_array = np.random.randint(10, size=(5,4))
my_other_array = np.random.randint(10, size=(10,5))
print(my_array, '\n')
print(my_other_array)

[[4 2 0 7]
 [2 2 8 9]
 [9 0 3 0]
 [3 0 4 3]
 [2 7 7 1]] 

[[0 3 0 6 2]
 [3 4 9 1 8]
 [1 0 9 4 1]
 [2 8 6 0 5]
 [7 2 7 9 4]
 [5 2 0 3 2]
 [9 7 4 5 0]
 [4 1 1 5 9]
 [0 8 1 1 7]
 [2 8 1 7 1]]


In [100]:
# Faça a multiplicação entre my_other_array e my_array
print('Shapes:', my_array.shape, my_other_array.shape)

# para esses formatos não posso multiplicar as matrizes usando a seqencia  my_array, my_other_array. 
#tenho que fazer casar o 5 com o 5 das matrizes
np.dot(my_other_array, my_array)

Shapes: (5, 4) (10, 5)


array([[ 69,  87, 104,  60],
       [123, 122, 118, 120],
       [ 84, 118,  66,  71],
       [148, 174, 145, 153],
       [138, 139, 122, 149],
       [164, 160, 128, 171],
       [128, 127, 115,  95],
       [107, 118,  78, 101],
       [ 80,  57,  41, 108],
       [ 61,  88,  52,  28]])

In [116]:
# Descubra a soma dos valores de cada linha de my_other_array

#AXIS-> linha =1 e coluna =0
np.sum (my_other_array, axis = 1)

array([11, 25, 15, 21, 29, 12, 25, 20, 17, 19])

In [129]:
my_array = np.random.randint(10, size=(5,4))
print(my_array)

[[9 4 2 9]
 [9 6 3 7]
 [2 3 2 8]
 [5 7 4 8]
 [7 9 6 5]]


In [130]:
# Usando reshape transforme a matriz acima em um vetor (Concatendo a linha de baixo na de cima)

my_array.reshape(20,)

array([9, 4, 2, 9, 9, 6, 3, 7, 2, 3, 2, 8, 5, 7, 4, 8, 7, 9, 6, 5])

In [131]:
np.array([[ 0,  1,  2,  3,  4,  5,  6,  7],
          [ 8,  9, 10, 11, 12, 13, 14, 15]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [145]:
# Gere a array anterior usando np.arange e a função reshapea
a= np.arange(16)
print (a)

print ('\n')
b= a.reshape(2,8)
print (b)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
